# Generated by Django 3.1.4 on 2021-04-05 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210405_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='field_name',
            new_name='poster_image',
        ),
    ]
