# Generated by Django 3.1.4 on 2021-04-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210405_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
